#Database for SEC Project

CREATE TABLE User (
	ID		int		PRIMARY KEY	NOT NULL,
	NAME	TEXT	NOT NULL
);

CREATE TABLE Location (
	COORDS	TEXT	PRIMARY KEY	NOT NULL
);

CREATE TABLE User_Loc (
	EPOCH	int		NOT NULL,
	ID_USER	int		NOT NULL,
	COORDS	TEXT	NOT NULL,
	PRIMARY KEY		(EPOCH, ID_USER),
	FOREIGN KEY		(ID_USER)	REFERENCES User (ID)
	FOREIGN KEY 	(COORDS)	REFERENCES Location (COORDS)
);