spring:
  datasource:
    url: jdbc:mysql://localhost:3307/AppDB?autoReconnect=true&useSSL=false
    username: appUser
    password: appUser!
  jpa:
    hibernate.ddl-auto: update
    database: mysql

grid:
  min: 0
  max: 50
  users: 20
  byzantineUsers: 5
  maxByzantineLocations: 5