version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7.33
    ports:
    - "3307:3306"
    container_name: mysqldb
    volumes:
    - milestone1_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=r00t!
      - MYSQL_DATABASE=AppDB
      - MYSQL_USER=appUser
      - MYSQL_PASSWORD=appUser!

volumes:
  milestone1_db_data: